version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    volumes:
      - ./:/home/app
    networks:
      - test-net
    ports:
      - "8545:8545"
      - "80:80"
      - "3000:3000"
    working_dir: /home/app
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.2.2

  db:
    image: postgres:alpine3.16
    networks:
      - test-net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

networks:
  test-net:
    external: true
